### ISSUE TITLE
Issue using with typescript

### ISSUE THREAD

**Issue by dsrkafuu** [pd4d10/vite-plugin-svgr#17]
The `@svgr/rollup` package works well when used directly in a vite project.

When I switch to this plugin it says:

```
[plugin:vite:svgr] Transform failed with 1 error:
E:/GitHub/skyline-overlay/src/assets/jobs/thm.svg:4:29: error: Expected ")" but found ":"

E:/GitHub/skyline-overlay/src/assets/jobs/thm.svg:4:29

Expected ")" but found ":"
2  |  import { SVGProps } from "react";
3  |  
4  |  const ReactComponent = (props: SVGProps<SVGSVGElement>) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" width="1em" height="1em" className="g-icon" {...props}><path d="M228 513q11 0 18 3 10 4 20 13.5t16 21.5q2 4 3 4l1-2q9-11 32-12 27-1 54 17 8 6 21 24 6 9 7 8.5t-1-8-6-15.5l-2-3q-4-8-7-13-7-9-17.5-16.5T343 523q-8-2-13-4-7-4-15-12-25-25-20-42 2-5 12-10-6-3-12-3-13 0-24-5-9-3-17.5-18.5T243 397q-1-6-.5-19t.5-19q-2-12-7-21-19-27-45-48-10-8-21-12 3 7 9 12.5t11 17.5q8 18 8 37 0 10-9 29.5t-9 29.5 7 21q4 6 14 16 8 9 10.5 13t2.5 10.5-2 8-9.5-1.5-18.5-10q-5-4-14.5-13.5T154 434q-9-7-21-9 1 4 4 6v1q22 20 28 37 2 6 2 18.5t3 16.5q4 6 15 16.5t14 10.5l1-2q8-16 28-16zm98-249q9 13 21 38t15.5 38.5T366 374q1 17-1 22-1 8-5 15 0-14-10-34-6-13-27-30l-6-5q-5-4-11-6l-5-1 11 15q10 13 14 24 8 19 8 44 0 11-9 29l-4 7q-1 5 1.5 16t7 17 14 11.5 20.5 8 26 11.5 28 22.5 26 29 17.5 23.5 6.5 16l3-4q2-7-1-15v-1q-15-52-40-85-15-19-24-40-8-18-9-33-2-20 11-40.5t12-32-4-21.5l3 2q4 4 6 10 2 7 2 17 0 4-4 17-7 25-4.5 38.5T444 463q7 9 9 11 6 10 8 23 2-5 2-10 0-3 2.5-14.5t6-18 12-15 12.5-9 8 3.5q3-18 1-36-2-24-39-59-20-18-32-46-13-30-14-65-2-43 41-85l3-3 13-15-13 7q-17 10-34 25-22 20-45 55-9 14-11 29-3 13 0 21 1 3 5.5 13.5T385 288q1 7 1 13l-5-10q-6-11-11-17-10-10-22-18-8-6-27-16-12-7-23-10l-8-3 12 12q15 13 24 25zm187 237q1 7-4.5 13.5T498 521t-9-5q-2-3-3-6-2 1-6 9t-4 19q0 18 14 37l18 25 1-4q1-4 0-6.5t-3-5.5q-4-6-4-13-1-15 8-27 3-5 7.5-8t8-1 1.5 10l-4 8q7-1 11-6 15-15 17-33t-8-28q-16-16-14-28 1-9 6-20 4-10 9-17l4-7q10-14 10-18-9 9-18 19-13 15-25 33-4 7-9.5 18.5T500 481l2 2q10 7 11 18zm89-74q4-5 14-15 19-18 26-26 12-15 16-29 2-7 2-24v-8q3 4 4 9 3 13 1 26-1 9-6 21.5T646 405t-21.5 24.5T606 446l-12 7 3 4q4 5 4 10-1 20-14 29-17 13-20 17.5t-2 10.5q3-4 8-6.5t10 1.5q2 2 1.5 6.5T582 533l-17 23q-8 10-11.5 22.5T553 603l3-9q5-11 10-19 18-26 39-37 15-8 34-13l2-11q3-13 10-21 7-10 18-16.5t19-6.5l5-1q14-1 18-2t11-6q9-6 15-13 9-10 13-22l2-9-5 6q-7 7-11 9-6 4-26 5l-8 1q-7 2-13 7l-9 6q0-4 2-8.5t8-10.5q8-10 17-14 22-10 32-22 7-7 10-17 1-6 2-17.5t2-16.5q4-23 27-43 20-16 44-24-8-1-16-1-18 3-35 10-24 9-40 29l-2 2q-6 8-10 11-7 5-14 3-13-4-14-24l1-13q0-17-.5-25t-8.5-24-17-29q-13-19-30-36-14-13-31-21 4 7 9 12 14 13 20 26 9 23 9 49 0 31-16 54-8 10-24.5 25.5T587 348q-2 13 4 24 4 10 2 21v1q-2 17-8 26l-23 34q0 1 16-9t24-18zm235 17q-6 6-13 15l-5 8q-6 7-12 10-4 1-12 2l-3 1q-8 1-17 0 6-7 11-16 3-6 4.5-19t0-27-6-26.5-9-19.5-11.5-12l4 9q2 3 2.5 17.5T769 417q-1 10-5 18-3 5-9 12.5t-9 12.5q-7 11-16.5 19T704 494q-31 14-49 32-7 7-14 20l-6 13q7-5 14-11 4-3 15.5-9t20.5-8.5 23-2 22 3.5q12 4 22 11 4-11 11-20 11-15 26-17l6-1q10 0 15-1 9-3 15-9 9-8 14-24l4-12q4-8 14-18l10-9q-17 0-30 12zm-96 226q-10 0-18 11-4 6-9 21-4 10-6.5 14t-8 7-10.5 0q-9-7-3-25 3-8 21-27l8-10q25-29 25-57 0-18-11-29.5T700 563q-31 0-46 21-1 1-2.5 1t-2.5-1q-4-7-9.5-12t-11.5-6-8 1l3 4q3 5 2 10-2 11-33 25-22 10-52 13-17 2-44 2h-2q-27 0-44-2-30-3-52-13-32-14-33-25h-1q-1-7 6-14-3-2-8.5-1t-11.5 6-9 12q-1 1-3 1t-2-1q-16-21-46-21-18 0-29.5 11.5T249 604q0 27 26 57l8 10q18 19 20 27 7 18-3 25-5 3-10.5 0t-7.5-7-6-14q-5-15-10-21-7-11-18-11-21 0-27 19-4 11 0 19t8 8v-6q1-6 4-9 5-6 12-6 5 0 8.5 4t5.5 10q6 19 14 27t14.5 11.5T302 751t14-3l3-3q1 13 6 25 7 18 23 29 6 4 16.5 9.5T381 818q12 8 22 19v8q0 5 8 11 10 7 27 12 24 7 57.5 7t56.5-7q17-5 27-12 8-6 8-11v-8q10-11 22-19 6-4 16.5-9.5T642 799q16-11 23-29 4-12 5-25l4 3q5 3 13 3t15-3.5 15-11.5 14-27q1-5 5-9t8-4q7-1 12 5 3 3 4 10l1 5q4 0 8-8t0-19q-7-19-28-19zm-399 33q-4 7-12 11v-5q0-6-2-12-4-10-13-20l-4-6q-19-22-22-34.5t1.5-23T302 600q14-6 32 9 9 8 14 18 3 7 3 13t-2 9-5 3q-6 0-8-3t-3-6q-6 0-5 12.5t13 16.5q5 1 10 0l1 4q0 5-2 11-2 8-8 16zm318 11q-8-4-13-11.5t-7-15.5q-2-6-2-11l1-5q5 2 10 1 12-4 12.5-16.5T657 643q-1 3-3 6t-8 3q-3 0-5-3t-2-9 3-13q5-10 14-18 18-15 32-9 7 3 11.5 13.5t1.5 23-22 34.5l-5 6q-8 10-12 20-2 7-2 12v5z" /></svg>;
   |                               ^
5  |  
6  |  export { ReactComponent };

    at failureErrorWithLog (E:\GitHub\skyline-overlay\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1493:15)
    at E:\GitHub\skyline-overlay\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1282:29
    at E:\GitHub\skyline-overlay\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (E:\GitHub\skyline-overlay\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (E:\GitHub\skyline-overlay\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23
```

It seems to indicate that Vite can't properly handle TS file output via SVGR.

**How to reproduce:**

https://github.com/dsrkafuu/skyline-overlay

My project above works well now when not using the `typescript` svtg option in `vite.config.ts`, when uncommenting the option and the issue occurs.

https://github.com/dsrkafuu/skyline-overlay/blob/7a4e49440f39aea1d7ef8338f7e9a3165c6e9cf7/vite.config.ts#L13-L17

**Comment by pd4d10** [comment]
Added `esbuildOptions` to handle this case:

```
esbuildOptions: { loader: 'tsx' }
```
