### ISSUE TITLE
Incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by ronaldruzicka** [pd4d10/vite-plugin-svgr#78]
After updating plaugin to version `3.1.0` I get this error:
```bash
> vite --port 3003 --host

✘ [ERROR] Failed to resolve entry for package "vite-plugin-svgr". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "vite-plugin-svgr" package [plugin externalize-deps]

    ../../node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1360:27:
      1360 │         let result = await callback({
           ╵                            ^
    at packageEntryFailure (file:///Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/vite@4.3.4_@types+node@18.16.3/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23384:11)
    at resolvePackageEntry (file:///Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/vite@4.3.4_@types+node@18.16.3/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23379:9)
    at tryNodeResolve (file:///Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/vite@4.3.4_@types+node@18.16.3/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:23115:20)
    at file:///Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/vite@4.3.4_@types+node@18.16.3/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:64371:40
    at requestCallbacks.on-resolve (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1360:28)
    at handleRequest (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^
    at setup (file:///Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/vite@4.3.4_@types+node@18.16.3/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:64360:27)
    at handlePlugins (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:776:5)
    at /Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:2163:15
    at new Promise (<anonymous>)
    at Object.build (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:2162:25)
    at build (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:2011:51)
    at bundleConfigFile (file:///Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/vite@4.3.4_@types+node@18.16.3/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:64323:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.ts:5:23:
      5 │ import svgrPlugin from 'vite-plugin-svgr';
        ╵                        ~~~~~~~~~~~~~~~~~~
failed to load config from /Users/rruzicka/Projects/abis-monorepo/apps/applicants/vite.config.ts
error when starting dev server:
Error: Build failed with 1 error:
../../node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1360:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "vite-plugin-svgr". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "vite-plugin-svgr" package
    at failureErrorWithLog (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/rruzicka/Projects/abis-monorepo/node_modules/.pnpm/esbuild@0.17.15/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
 ELIFECYCLE  Command failed with exit code 1.
ERROR: command finished with error: command (/Users/rruzicka/Projects/abis-monorepo/apps/applicants) pnpm run dev exited (1)
```
Anyone having the same issue?

**Versions:**
```json
"vite": "^4.3.4",
"vite-plugin-svgr": "^3.1.0"
```

**Comment by pd4d10** [comment]
Thanks for the report, please try v3.2.0, which recovers the CJS entry and should solve this issue.

**Comment by ronaldruzicka** [comment]
super fast reply 🙂 thanks that worked! 👍
