### ISSUE TITLE
"incorrect casing" error after upgrade to 4.1.0

### ISSUE THREAD

**Issue by barbalex** [pd4d10/vite-plugin-svgr#95]
I have had a lot of issues since upgrading to 4.0.0.

Some were solved by reverting the include pattern to what it was before (https://github.com/pd4d10/vite-plugin-svgr/issues/91#issuecomment-1732028802).

One only turned up as error in production (might have been a warning in dev): ```Failed to execute 'createElement' on 'Document': The tag name provided ('/assets/101-021d24df.svg') is not a valid name.```. Not sure about this one, I am not looking forward to promoting the next version of my project to production.

The one I am facing now in development is:
```
@react-refresh:267 Warning: </src/components/Projekte/Karte/layers/Pop/statusGroupSymbols/100.svg?react /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    at /src/components/Projekte/Karte/layers/Pop/statusGroupSymbols/100.svg?react
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at div
    at ContextMenuTrigger (http://localhost:5173/src/modules/react-contextmenu/ContextMenuTrigger.js:53:5)
    at Row (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at div
    at Pop (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at PopFolder (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at ApFolders (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at div
    at Aps (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at Ap (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at ProjektNode (http://localhost:5173/src/components/Projekte/TreeContainer/Tree/Root/Projekt/index.jsx?t=1698308651647:21:3)
    at TreeRoot (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at TreeComponent (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at Suspense
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=082e3f10:18:5)
    at MyErrorBoundary (http://localhost:5173/src/components/shared/ErrorBoundary.jsx:192:3)
    at TreeContainer (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at Suspense
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at div
    at Pane2 (http://localhost:5173/node_modules/.vite/deps/react-split-pane.js?v=082e3f10:1782:5)
    at div
    at SplitPane2 (http://localhost:5173/node_modules/.vite/deps/react-split-pane.js?v=082e3f10:1913:5)
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at ProjektContainer (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at Projekte (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:3405:5)
    at Outlet (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:3728:26)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at ProtectedRoute (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:3405:5)
    at Outlet (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:3728:26)
    at Suspense
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-M4JZEDWM.js?v=082e3f10:1545:45
    at AppBarComponent (http://localhost:5173/node_modules/.vite/deps/mobx-react-lite.js?v=082e3f10:284:12)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:3405:5)
    at RenderErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:3365:5)
    at DataRoutes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:4376:5)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:3735:15)
    at RouterProvider (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=082e3f10:4249:5)
    at RouterComponent
    at Suspense
    at SnackbarProvider2 (http://localhost:5173/node_modules/.vite/deps/notistack.js?v=082e3f10:1245:24)
    at ThemeProvider (http://localhost:5173/node_modules/.vite/deps/chunk-NZHYSJQ4.js?v=082e3f10:3087:5)
    at ThemeProvider2 (http://localhost:5173/node_modules/.vite/deps/chunk-NZHYSJQ4.js?v=082e3f10:3146:5)
    at ThemeProvider (http://localhost:5173/node_modules/.vite/deps/@mui_material_styles.js?v=082e3f10:296:12)
    at StyledEngineProvider (http://localhost:5173/node_modules/.vite/deps/chunk-NZHYSJQ4.js?v=082e3f10:943:5)
    at QueryClientProvider (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-query.js?v=082e3f10:2715:3)
    at ApolloProvider (http://localhost:5173/node_modules/.vite/deps/@apollo_client.js?v=082e3f10:5697:19)
    at App
```

What baffles me is that this only happens in one file. Dozens of other files import svg without issues (in development...).

If I use
```js
import TpopSvg100 from '../../Karte/layers/Tpop/statusGroupSymbols/100.svg'
```
instead of
```js
import TpopSvg100 from '../../Karte/layers/Tpop/statusGroupSymbols/100.svg?react'
```
this does not happen.

I am not feeling good with the state of importing svg's using vite right now. Appending ?react in some imports but not in others just to circumvent weird errors seems way too hacky to me.

**Comment by trungpham71198** [comment]
I was able to address the precise issue you were facing.

`vite.config.ts`
<img width="377" alt="image" src="https://github.com/pd4d10/vite-plugin-svgr/assets/58923438/baeed987-778a-41ae-a323-99ce871737a6">

`import TpopSvg100 from '../../Karte/layers/Tpop/statusGroupSymbols/100.svg'` => You may enter in this way, and it will function.

**Comment by barbalex** [comment]
Yes that works, as I wrote above (sorry for not being clear enough). 

What I do not understand is why
```js
import TpopSvg100 from '../../Karte/layers/Tpop/statusGroupSymbols/100.svg?react'
```
does not work.

Appending ?react seems to be the correct way to do it, so why can I do it sometimes but others it fails?

**Comment by sliptype** [comment]
fwiw I was getting this same error because my import path was wrong and the svg didn't exist at the specified path

**Comment by gabriofr** [comment]
I had the same error and solved it by removing a leftover declaration file from CRA were we handled svg's
Hope it helps: 

```typescript
declare module "*.svg" {
  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
  export default content;
}
```

**Comment by AdrianDiazCode** [comment]
Why there's no info/update on this?
